server:
  port: 0000

spring:
  # 数据源配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql_host:3306/database
    username: username
    password: password
  # 定时任务配置
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
  jackson:
    time-zone: GMT+8

# mybatis plus 配置
mybatis-plus:
  global-config:
    db-config:
      id-type: none
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    # sql 打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

bot:
  telegram:
    # 配置是否使用连接代理
    proxy:
      enable: false
      host: host
      port: 0000
      type: SOCKS4
    # 配置 Webhook 信息
    webhook:
      enable: false
      url: https://example.com
    # 配置 bot 信息
    base:
      name: 岁寒
      token: token
